services:
  # A Docker web service
  - type: web
    name: XList+Xria2
    env: docker
    repo: https://github.com/jinenge/AList-Aria2-Render.git # optional
    region: Singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgres
        sync: false
      - key: DB_HOST
        value: db.bit.io
        sync: false
      - key: DB_PORT
        value: 5432
        sync: false
      - key: DB_USER
        value: jinenge
        sync: false
      - key: DB_PASS
        value: v2_43pUm_UPAwLBXRmX523PhxCfWPKgZ
        sync: false
      - key: DB_NAME
        value: jinenge/jinenyy
        sync: false
      - key: DB_TABLE_PREFIX
        value: alist_
        sync: false
